# Generated by Django 4.2.5 on 2023-09-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tabla_load',
            new_name='lentes',
        ),
        migrations.AlterModelTable(
            name='lentes',
            table='lentes',
        ),
    ]
