# Generated by Django 4.2.5 on 2023-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tabla_load_lentes_alter_lentes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lentes',
            name='descripcion',
            field=models.CharField(max_length=800),
        ),
    ]
